version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: plrbase/home-doc-backend:latest 
    ports:
      - "8081:8080" # Exposes backend on host port 8080
    volumes:
      - ./backend/uploads:/root/uploads # Persist uploaded files
      - ./backend-data:/root/data     # Persist SQLite database
    # networks:
      # - app-network

  frontend:
    build:
      context: ./frontend 
      dockerfile: Dockerfile
    image: plrbase/home-doc-frontend:latest 
    ports:
      - "80:80" # Exposes frontend on host port 3000 (Nginx serving on port 80 in container)
    depends_on:
      - backend
    # networks:
      # - app-network

# networks:
  # app-network:
    # driver: bridge
